pa_user_index:
    path:    /index
    defaults: { _controller: PAUserBundle:User:index }
    
pa_user_add:
    path:    /add
    defaults: { _controller: PAUserBundle:User:add }
    
pa_user_create:
    path:    /create
    defaults: { _controller: PAUserBundle:User:create }
    methods: POST
    
pa_user_edit:
    path:    /edit/{id}
    defaults: { _controller: PAUserBundle:User:edit }
    
pa_user_update:
    path:    /update/{id}
    defaults: { _controller: PAUserBundle:User:update }
    methods: [POST, PUT]
    
pa_user_view:
    path:    /view/{id}
    defaults: { _controller: PAUserBundle:User:view }
    
pa_user_delete:
    path:    /delete/{id}
    defaults: { _controller: PAUserBundle:User:delete }
    methods: [POST, DELETE]
    
pa_user_redirect_add:
    path: /create
    defaults:
        _controller: PAUserBundle:User:add
        path: /add
        permanent: true
        
pa_user_redirect_edit:
    path: /update/{id}
    defaults:
        _controller: PAUserBundle:User:edit
        path: /edit/{id}
        permanent: true